#!/usr/bin/env python3

# First see ../exporter/ for how to generate the inputs to this program.

import os, sys, json
import itertools, functools
from collections import defaultdict, Counter

from json_dumps_but_smaller import json_dump
from ap_data import (
    ap_item_names,
    trap_names,
    small_progressive_groups, large_progressive_groups,
)

here = os.path.dirname(__file__)
formatted_input = os.path.join(here, "ap-dump-full.json")
formatted_input_planets = {
    planet: os.path.join(here, "ap-dump-full-{}.json".format(planet))
    for planet in ["vulcanus", "gleba", "fulgora"]
}
main_output = os.path.join(here, "ap-dump.json")
output_planets = {
    planet: os.path.join(here, "ap-dump-{}.json".format(planet))
    for planet in ["vulcanus", "gleba", "fulgora"]
}
output_names_py = os.path.join(here, "generated_names.py")
output_ids_py = os.path.join(here, "generated_ids.py")

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("input", nargs="?", metavar="~/software/factorio/script-output/ap-dump.json", help=
        "See ../exporter/ for how to generate this.")
    args = parser.parse_args()

    if args.input:
        recieve_input(args.input)

    ready_yet = check_inputs()
    if not ready_yet:
        sys.exit("Redo the export with the remaining starting planets")
    process()
    print("Done!")

header = """\
#################################################
# This file is generated by ./import-ap-dump.py #
#################################################

"""

names_header = """\
# This file provides spell checking in the Python type system,
# for example catching the misspelling "metalurgic", which is common for me.
# Because item, plant, technology, etc. names are all mixed together,
# this doesn't give proper type checking, just spell checking;
# You're on you're own for remembering the difference between accumulator and electric_energy_accumulators.

"""

artificial_names_header = """\

# This next block of names comes from ap_data.py rather than from Factorio itself.
"""

ids_header = """\
# This file provides what is absolutely needed on apworld import.
# Other imports in this apworld are deferred until this apworld is actually being used for generation, client, etc.

"""

def recieve_input(input_path):
    # Import the json data and format it.
    with open(input_path, "rb") as f:
        the_data = json.load(f)
    starting_planet = "nauvis"
    if "planet-discovery-nauvis" in the_data["technology"]:
        # This is using Any Planet Start mod by _CodeGreen.
        if the_data["technology"]["planet-discovery-vulcanus"].get("hidden", False):
            starting_planet = "vulcanus"
        elif the_data["technology"]["planet-discovery-gleba"].get("hidden", False):
            starting_planet = "gleba"
        elif the_data["technology"]["planet-discovery-fulgora"].get("hidden", False):
            starting_planet = "fulgora"
        else: assert False, "which planet start is this?"
        with open(formatted_input_planets[starting_planet], "w") as f:
            json_dump(the_data, f)
    else:
        with open(formatted_input, "w") as f:
            json_dump(the_data, f)

def check_inputs():
    ready_yet = True
    for file_name in [formatted_input] + list(formatted_input_planets.values()):
        got_it = os.path.isfile(file_name)
        if got_it:
            print("FOUND: " + file_name)
        else:
            print("MISSING: " + file_name)
        if not got_it:
            ready_yet = False
    return ready_yet

def process():
    with open(formatted_input, "rb") as f:
        main_data = prune_data(json.load(f))
    with open(main_output, "w") as f:
        json_dump(main_data, f)

    # Store a diff of the data for each planet start,
    # and merge it all together for generating names and ids.
    merged_data = {k: dict(v) for k, v in main_data.items()}
    for planet, planet_file_name in formatted_input_planets.items():
        with open(formatted_input_planets[planet], "rb") as f:
            planet_data = prune_data(json.load(f))

        assert planet_data.keys() == main_data.keys(), "there's no way any-planet-start mod introduced new prototype types"
        diff_data = defaultdict(dict)
        for prototype_type in main_data.keys():
            main_prototypes = main_data[prototype_type]
            planet_prototypes = planet_data[prototype_type]
            for deleted_prototype_name in main_prototypes.keys() - planet_prototypes.keys():
                # e.g. fulgora removes scrap-recycling-productivity and adds -1 through -4 instead.
                diff_data[prototype_type][deleted_prototype_name] = None
            for prototype_name, prototype_data in planet_prototypes.items():
                if prototype_data != main_prototypes.get(prototype_name, None):
                    diff_data[prototype_type][prototype_name] = prototype_data
            merged_data[prototype_type].update(planet_prototypes)
        with open(output_planets[planet], "w") as f:
            json_dump(dict(diff_data), f)

    generate_names(merged_data)
    generate_ids(merged_data)

progressive_pseudo_item_names = set()

def generate_names(the_data):
    # Generate spellchecking names.
    already_generated = {}
    builtin_name_lines = []
    for prototype_type, prototype_decls in the_data.items():
        if prototype_type == "projectile": continue # Never interesting.
        for name in prototype_decls.keys():
            python_name = to_snake(name)
            line = "{} = {}".format(python_name, json.dumps(name))
            if python_name not in already_generated:
                builtin_name_lines.append(line + "\n")
                already_generated[python_name] = line
            else:
                assert already_generated[python_name] == line, "identifier collision: " + line
    builtin_name_lines.sort()

    artificial_name_lines = []
    for name in ap_item_names + trap_names:
        python_name = to_snake(name.lower().replace(" ", "_"))
        line = "{} = {}".format(python_name, json.dumps(name))
        assert python_name not in already_generated, "identifier collision: " + line
        already_generated[python_name] = line
        artificial_name_lines.append(line + "\n")

    # Progressive pseudo item names.
    assert all(v == 1 for v in Counter(itertools.chain.from_iterable(small_progressive_groups.values())).values()), "duplicate technology"
    assert all(v == 1 for v in Counter(itertools.chain.from_iterable(large_progressive_groups.values())).values()), "duplicate technology"
    for progressive_technology_stacks in [small_progressive_groups, large_progressive_groups]:
        for name, technology_names in progressive_technology_stacks.items():
            for technology_name in technology_names:
                assert technology_name in the_data["technology"].keys(), "technology not found: " + technology_name
            if name in the_data["technology"].keys():
                # Some of the progressive stacks are just the name of the infinite tech.
                continue
            progressive_pseudo_item_names.add(name)
    for name in sorted(progressive_pseudo_item_names):
        python_name = to_snake(name)
        line = "{} = {}".format(python_name, json.dumps(name))
        assert python_name not in already_generated, "identifier collision: " + line
        already_generated[python_name] = line
        artificial_name_lines.append(line + "\n")

    with open(output_names_py, "w") as f:
        f.write(header)
        f.write(names_header)
        f.writelines(builtin_name_lines)
        f.write(artificial_names_header)
        f.writelines(artificial_name_lines)

def generate_ids(the_data):
    # Generate AP id numbers.
    factorio_base_id = 2 ** 17
    id_cursor = factorio_base_id
    def next_id():
        nonlocal id_cursor
        id_cursor += 1
        return id_cursor
    # Technology locations and items
    ap_location_name_to_id = {}
    ap_item_name_to_id = {}
    # Synthetic locations first, because they never change (smaller git diff when there are later changes).
    for i in range(1000):
        ap_location_name_to_id["ap-{:03}_location".format(i)] = next_id()
    id_cursor = factorio_base_id * 2
    for technology_name in sorted(the_data["technology"].keys()):
        assert not "_" in technology_name, "that's the delimiter we use for our special suffixes: " + technology_name
        location_name = technology_name + "_location"
        ap_location_name_to_id[location_name] = next_id()
        ap_item_name_to_id[technology_name] = next_id()
    # Progressive pseudo items
    id_cursor = factorio_base_id * 3
    for progressive_technology_name in sorted(progressive_pseudo_item_names):
        if progressive_technology_name in ap_item_name_to_id:
            # Some of the progressive stacks are just the name of the infinite tech.
            continue
        ap_item_name_to_id[progressive_technology_name] = next_id()
    # New items
    id_cursor = factorio_base_id * 4
    for name in ap_item_names:
        ap_item_name_to_id[name] = next_id()
    # Traps
    id_cursor = factorio_base_id * 5
    for trap_name in trap_names:
        ap_item_name_to_id[trap_name] = next_id()

    with open(output_ids_py, "w") as f:
        f.write(header)
        f.write(ids_header)
        f.write("ap_location_name_to_id = {}\n".format(json.dumps(ap_location_name_to_id, indent=4)))
        f.write("\n")
        f.write("ap_item_name_to_id = {}\n".format(json.dumps(ap_item_name_to_id, indent=4)))

def to_snake(name):
    if name[0].isdigit():
        name = "_" + name
    return name.lower().replace("-", "_")


# These are the properties we care about in the randomizer logic.
Base = {
    "minable": {
        "results": [{"name": str}],
        "result": str,
        "required_fluid": str,
    },
    # Does anything power this machine?
    "energy_source": {
        "type": str,
        "usage_priority": str, # for type=electric
        "fuel_categories": [str], # for type=burner
        # TODO: can't figure out how to get useful information out of type=heat.
    },
    "burner": {
        # Some machines (e.g. fusion-reactor) specify an additional energy source with this field.
        "fuel_categories": [str],
    },
    # Steel furances cannot be build on space platforms, for example.
    "surface_conditions": [{
        "property": str,
        "min": float,
        "max": float,
    }],
    "heating_energy": str,
    # Several entities and tiles get autoplaced in various ways. This is one of the ways.
    "autoplace": {
        "control": str,
        "tile_restriction": [str],
    },
    # If either of these are true, we probably don't care about this.
    # Exception: vehicle guns tell us that spidertron can fire capture robot rockets.
    "hidden": bool,
    "parameter": bool,
}

CraftingMachine = {**Base,
    "crafting_categories": [str],
    "fixed_recipe": str,
}

SpaceLocation = {**Base,
    "solar_power_in_space": float, # It's a percent, not a multiplier. Default is 1%.
    "asteroid_spawn_definitions": [{
        "asteroid": str,
    }],
}

Vehicle = {**Base,
    # Only logic relevant if the vehicle can fire capture robot rockets.
    "guns": [str],
}

Item = {**Base,
    "place_result": str,
    "place_as_tile": {"result": str},
    "plant_result": str,
    "fuel_category": str,
    "burnt_result": str,
    "spoil_ticks": int,
    "spoil_result": str,
}

keep_props = {
    "accumulator": {str: Base},
    "agricultural-tower": {str: Base},
    "ammo": {str: {
        "ammo_category": str,
        # This is interesting for capture-robot-rocket:
        "ammo_type": {
            "action": {"action_delivery": {"projectile": str }},
            "target_filter": [str],
        },
    }},
    "ammo-turret": {str: {**Base,
        "attack_parameters": {"ammo_category": str},
    }},
    "armor": {str: Item},
    # This is never logically relevant, and it's a little special. Descope for now:
    #"artillery-wagon": {str: Vehicle},
    "assembling-machine": {str: CraftingMachine},
    "asteroid": {str: {
        "dying_trigger_effect": [{
            "type": str,
            "asteroid_name": str, # for type=create-asteroid-chunk
            "entity_name": str, # for type=create-entity
        }],
        "max_health": float,
        "resistances": [{
            "type": str,
            "decrease": float,
            "percent": float,
        }],
    }},
    "asteroid-chunk": {str: Base},
    "asteroid-collector": {str: Base},
    "boiler": {str: {**Base,
        "target_temperature": float,
    }},
    "capsule": {str: Item},
    "capture-robot": {str: {}},
    "car": {str: Vehicle},
    "cargo-landing-pad": {str: {}},
    "character": {str: {
        "crafting_categories": [str],
        "mining_categories": [str],
    }},
    "construction-robot": {str: Base},
    "electric-pole": {str: Base},
    "electric-turret": {str: Base}, # TODO: add attack_parameters if we care.
    "fish": {str: Base},
    "fluid": {str: Base},
    "fluid-turret": {str: Base}, # TODO: add attack_parameters if we care.
    "furnace": {str: CraftingMachine},
    "fusion-generator": {str: Base},
    "fusion-reactor": {str: Base},
    "generator": {str: {**Base,
        "maximum_temperature": float,
    }},
    "gun": {str: {**Base,
        "attack_parameters": {"ammo_category": str},
    }},
    "heat-pipe": {str: Base},
    "item": {str: Item},
    "item-with-entity-data": {str: Item},
    "lab": {str: {**Base,
        "inputs": [str],
    }},
    "lightning-attractor": {str: {**Base,
        "efficiency": float,
    }},
    "logistic-container": {str: {**Base,
        "logistic_mode": str,
    }},
    "logistic-robot": {str: Base},
    "mining-drill": {str: {**Base,
        "resource_categories": [str],
        "input_fluid_box": {}, # Burner mining drill cannot mine uranium.
    }},
    "module": {str: Item},
    "offshore-pump": {str: Base},
    "pipe": {str: Base},
    "pipe-to-ground": {str: Base},
    "planet": {str: {**SpaceLocation,
        "map_gen_settings": {
            "autoplace_settings": {
                "tile": {"settings": {str: {}}},
                "entity": {"settings": {str: {}}},
            },
            "autoplace_controls": {str: {}},
            "territory_settings": {"units": [str]}, # Demolishers.
        },
        "surface_properties": {str: float},
        "lightning_properties": {},
        "entities_require_heating": bool,
    }},
    "plant": {str: Base},
    "projectile": {str: {
        "action": {"action_delivery": {"target_effects": [{
            "type": str,
            "damage": {"amount": float, "type": str},
            "entity_name": str, # Only interesting for capture-robot-rocket.
        }]}},
    }},
    "pump": {str: Base},
    "quality": {str: {**Base,
        "next": str,
    }},
    "rail-planner": {str: Item}, # rail and rail-ramp are in here.
    "reactor": {str: Base},
    "recipe": {str: {**Base,
        "enabled": bool,
        "category": str,
        "ingredients": [{
            "type": str,
            "name": str,
            "amount": float, # uint16 for item, fixed-precision decimal for fluid.
            "ignored_by_stats": float,
            # Capturing all fields because we need to preserve all fields when doing modifications to recipes.
            "temperature": float,
            "minimum_temperature": float,
            "maximum_temperature": float,
            "fluidbox_index": int,
            "fluidbox_multiplier": int,
        }],
        "energy_required": float,
        "results": [{
            "type": str,
            "name": str,
            "amount": int,
            # ignoring amount_min and amount_max, as they are never used in vanilla.
            "probability": float,
            "ignored_by_stats": int,
            "extra_count_fraction": float,
            "temperature": float,
        }],
        "hide_from_player_crafting": bool,
    }},
    "repair-tool": {str: {}},
    "resource": {str: {**Base,
        "category": str,
    }},
    "roboport": {str: Base},
    "rocket-silo": {str: {**CraftingMachine,
        "rocket_parts_required": int,
    }},
    "segmented-unit": {str: {
        "corpse": str,
    }},
    "simple-entity": {str: Base},
    "solar-panel": {str: Base},
    "space-connection": {str: {**SpaceLocation,
        "from": str,
        "to": str,
    }},
    "space-location": {str: SpaceLocation},
    "space-platform-starter-pack": {str: Item},
    "spider-vehicle": {str: Vehicle},
    "storage-tank": {str: Base},
    "surface-property": {str: {
        "default_value": float,
    }},
    "technology": {str: {**Base,
        "research_trigger": {
            "type": str,
            "entity": str,
            "item": str,
            "fluid": str,
            "count": int,
        },
        "unit": {
            "count": int,
            "count_formula": str,
            "time": float,
            "ingredients": [(str, int)],
        },
        "ignore_tech_cost_multiplier": bool,
        "max_level": str, # Always "infinite" or omitted in vanilla.
        "prerequisites": [str],
        "effects": object, # Preserve verbatim.
    }},
    "thruster": {str: Base},
    "tile": {str: {**Base,
        "fluid": str,
    }},
    "tool": {str: Item},
    "tree": {str: Base},
    "unit-spawner": {str: {**Base,
        "loot": [{"item": str}],
    }},
    "wall": {str: Base},
}

def prune_data(data):
    def recurse(data, schema):
        if schema == object:
            return data
        if schema == str:
            assert type(data) == str, "expected str: " + repr(data)
            return data
        if schema == bool:
            assert type(data) == bool, "expected bool: " + repr(data)
            return data
        if schema == int:
            assert type(data) in (int, float), "expected number: " + repr(data)
            # Recipe product amounts are sometimes floats in the prototype data (example "speed-module-recycling").
            # They get truncated to int16 by the runtime phase.
            return int(data)
        if schema == float:
            assert type(data) in (int, float), "expected number: " + repr(data)
            return data
        if type(schema) == dict and schema.keys() == {str}:
            [v_schema] = schema.values()
            return {k: recurse(v, v_schema) for k, v in data.items()}
        if type(schema) == dict and all(type(k) == str for k in schema.keys()):
            return {k: recurse(data[k], v_schema) for k, v_schema in schema.items() if k in data}
        if type(schema) == list and len(schema) == 1:
            [v_schema] = schema
            if type(data) == list:
                return [recurse(v, v_schema) for v in data]
            elif data == {}:
                return [] # Lua makes no distinction between [] and {}.
            else:
                return recurse(data, v_schema) # Fallback to guessing the list is instead a single item.
        if type(schema) == tuple:
            assert type(data) == list and len(schema) == len(data), "expected tuple of length {}: {}".format(len(schema), repr(data))
            return [recurse(v, v_schema) for v, v_schema in zip(data, schema)]
        assert False, "unrecognized schema: " + repr(schema)
    return recurse(data, keep_props)

if __name__ == "__main__":
    main()
